name: Hello World example
on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Mostrar mensaje
        run: |
          echo "Hola mundo!"
      - name: Mostrar fecha
        run: date
      - run: ls -l